### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DoumanAsh** [DoumanAsh/lazy-socket.rs#2]
- [ ] Replace `net::SocketAddr` with own struct. From #1 
- [ ] Add platform specific extensions as trait (e.g. `SocketUnixExt`). From  #1 
- [x] Pin next version of libc(current 0.2.21) as only versions above have `accept4`. Ref #3. Done https://github.com/DoumanAsh/lazy-socket.rs/commit/78a9c83215920ccdc805d393f3146b7ea2caa648
